version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install nose2
            pip install coverage
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover test_number_unit
            nose2 -v --with-coverage
            nose2 -v --with-coverage --coverage-report html
      - store_artifacts:
          path: test-reports
          destination: test-reports
